In [1]:
import pandas as pd

In [2]:
path = '../Allwords.csv'
pd1 = pd.read_csv(path)
pd1.head()

     Negative   Positive
0     2-faced         a+
1     2-faces     abound
2    abnormal    abounds
3     abolish  abundance
4  abominable   abundant

In [3]:
pd2 = pd1.set_index('Negative')
pd2 = pd2.drop('Positive', axis=1)
pd3 = pd1.set_index('Positive')
pd3 = pd3.drop('Negative', axis=1)
pd3.head()

Empty DataFrame
Columns: []
Index: [a+, abound, abounds, abundance, abundant]

In [4]:
def sentScore(split_text):
    posCount = 0
    negCount = 0
    posArray = []
    negArray = []
    for x in split_text:
        try:
            posArray.append(pd3.loc[x])
        except KeyError:
            pass
        try:
            negArray.append(pd2.loc[x])
        except KeyError:
            pass
    posCount = len(posArray)
    negCount = len(negArray)
#     print(posArray)
#     print(negArray)
    return((posCount - negCount)/len(split_text)) #, posCount, negCount)

In [5]:
path2 = '../Datafiniti_Hotel_Reviews.csv'

In [6]:
df2 = pd.read_csv(path2)

In [7]:
df2.head()

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,keys,latitude,...,reviews.dateSeen,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sourceURLs,websites
0,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-08-03T00:00:00Z,2016-07-26T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,Our experience at Rancho Valencia was absolute...,Best romantic vacation ever!!!!,NaN,NaN,Paula,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
1,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-08-02T00:00:00Z,2016-08-26T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,Amazing place. Everyone was extremely warm and...,Sweet sweet serenity,NaN,NaN,D,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
2,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-11-15T00:00:00Z,2016-08-23T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,We booked a 3 night stay at Rancho Valencia to...,Amazing Property and Experience,NaN,NaN,Ron,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
3,AVwdOclqIN2L1WUfti38,2015-11-28T19:19:35Z,2018-09-10T21:06:16Z,7520 Teague Rd,"Hotels,Hotels and motels,Travel agencies and b...",Accommodation & Food Services,Hanover,US,us/md/hanover/7520teaguerd/-2043779672,39.155929,...,"2016-05-21T00:00:00Z,2016-07-31T00:00:00Z",2.0,https://www.tripadvisor.com/Hotel_Review-g4118...,Currently in bed writing this for the past hr ...,"Never again...beware, if you want sleep.",Richmond,VA,jaeem2016,http://www.yellowbook.com/profile/aloft-arunde...,http://www.starwoodhotels.com/alofthotels/prop...
4,AVwdOclqIN2L1WUfti38,2015-11-28T19:19:35Z,2018-09-10T21:06:16Z,7520 Teague Rd,"Hotels,Hotels and motels,Travel agencies and b...",Accommodation & Food Services,Hanover,US,us/md/hanover/7520teaguerd/-2043779672,39.155929,...,2016-07-31T00:00:00Z,5.0,https://www.tripadvisor.com/Hotel_Review-g4118...,I live in Md and the Aloft is my Home away fro...,ALWAYS GREAT STAY...,Laurel,MD,MamaNiaOne,http://www.yellowbook.com/profile/aloft-arunde...,http://www.starwoodhotels.com/alofthotels/prop...

In [8]:
df32 = df2[['reviews.rating', 'reviews.text']]

In [9]:
from sklearn.model_selection import train_test_split
df33, x_test, y_train, y_test = train_test_split(df32['reviews.text'], df32['reviews.rating'], random_state=1)

In [12]:
rate_list = []
math_list = []
actual_list = []

for x in range(len(df33)):
    splitter = df33.iloc[x].split()
#     print(splitter)
    senty = sentScore(splitter)
    if senty > 0:
        senty2 = 1
    elif senty < 0:
        senty2 = 0
    else:
        senty2 = 2
    #print(str(senty2) + ' Actual Rating:  ' + str(df33.iloc[x]['reviews.rating']))
    rate_list.append(senty2)
    math_list.append(senty)
    actual_list.append(df33.iloc[x])

AttributeError: 'float' object has no attribute 'split'

In [13]:
df44 = pd.DataFrame(data=rate_list)
df45 = pd.DataFrame(data=math_list)
df46 = pd.DataFrame(data=actual_list)

In [14]:
df77 = df44.join(df45, lsuffix='a')

In [15]:
df77 = df77.join(df46, rsuffix='b')

In [16]:
df77.set_axis(['Guess', 'Score', 'Rating'], axis=1, inplace=True)

In [17]:
df77

      Guess     Score                                             Rating
0         2  0.000000  Bad: We had the bad luck of staying in a room ...
1         1  0.104167  We have stayed at this motel many times while ...
2         1  0.064103  We traveled to Tarpon Springs for two reasons:...
3         1  0.033898  We arrived early and we hadn't slept. Our room...
4         1  0.013889  Not in the greatest area, but cant complain ab...
...     ...       ...                                                ...
3528      2  0.000000          Good: everithing beyond our expectations.
3529      1  0.032787  Might have stayed in a BW a handful of times o...
3530      1  0.026316  Barely a 4-star. Bathroom looked like somethin...
3531      0 -0.069767  Nice hotel and very nice staff. Big problem wi...
3532      1  0.008746  Today with the economy the way it is everyone ...

[3533 rows x 3 columns]

In [18]:
df88 = df77.set_index('Guess')

In [19]:
poop = df77.groupby('Guess')

In [20]:
trueP = 0
falseP = 0
trueN = 0
falseN = 0
trueNu = 0
falsePNu = 0
falseNNu = 0
falseNuP = 0
falseNuN = 0

for x in range(len(df77)):
#     print(df77.iloc[x])
    if df77.iloc[x][0] == 1 and df77.iloc[x][2] >= 4:
        trueP += 1
    if df77.iloc[x][0] == 1 and df77.iloc[x][2] <= 2:
        falseP += 1
    if df77.iloc[x][0] == 1 and df77.iloc[x][2] < 4 and df77.iloc[x][2] > 2:
        falsePNu += 1
    if df77.iloc[x][0] == 0 and df77.iloc[x][2] >= 4:
        falseN += 1
    if df77.iloc[x][0] == 0 and df77.iloc[x][2] <= 2:
        trueN += 1
    if df77.iloc[x][0] == 0 and df77.iloc[x][2] < 4 and df77.iloc[x][2] > 2:
        falseNNu += 1
    if df77.iloc[x][0] == 2 and df77.iloc[x][2] < 4 and df77.iloc[x][2] > 2:
        trueNu += 1
    if df77.iloc[x][0] == 2 and df77.iloc[x][2] >= 4:
        falseNuP += 1
    if df77.iloc[x][0] == 2 and df77.iloc[x][2] <= 2:
        falseNuN += 1

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
accur = (trueP + trueN + trueNu) / (trueP + trueN + trueNu + falseP + falsePNu + falseNuN + falseN + falseNNu + falseNuP)

In [ ]:
print(accur)

In [ ]:
confuM = [[trueP, falseP, falsePNu] , [falseN, trueN, falseNNu] , [falseNuN, falseNuP, trueNu]]

In [ ]:
for x in confuM:
    print(x)